spring.application.name=product-service
spring.data.mongodb.uri=${MONGODBURI}
server.port=0
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
product.pagination.max-page-size=100